//! `ft commands list` — introspect the command registry.
//!
//! Walks every `CommandDef` in the build-time `CommandRegistry` and
//! prints it in one of three formats: a terminal table (default),
//! NDJSON (one JSON object per line), or grouped JSON.

use anyhow::Result;
use clap::{Args, Subcommand, ValueEnum};

use crate::tui::registry::{self, CommandDef, CommandScope};

#[derive(Args)]
pub struct CommandsArgs {
    #[command(subcommand)]
    pub command: CommandsCommand,
}

#[derive(Subcommand)]
pub enum CommandsCommand {
    /// List every command in the registry
    List(ListArgs),
    /// Generate (or check) the `docs/keybindings.md` markdown reference
    Docs(DocsArgs),
}

#[derive(Args)]
pub struct DocsArgs {
    /// Path to write to (or check against). Defaults to
    /// `docs/keybindings.md` in the current directory.
    #[arg(long)]
    pub out: Option<std::path::PathBuf>,

    /// Don't write — compare the generator output to the file at
    /// `--out` and exit non-zero if they differ. Used by CI to gate
    /// drift between the registry and the committed docs.
    #[arg(long)]
    pub check: bool,
}

#[derive(Args)]
pub struct ListArgs {
    /// Output format
    #[arg(long, value_enum, default_value_t = OutputFormat::Table)]
    format: OutputFormat,

    /// Scope filter (`global`, `tab`, `modal`, or a specific
    /// `tab/<name>` / `modal/<name>`)
    #[arg(long)]
    scope: Option<String>,

    /// Filter by `opens_modal` (true / false). Without the flag, both
    /// kinds are shown.
    #[arg(long)]
    opens_modal: Option<bool>,
}

#[derive(ValueEnum, Clone, Copy, Debug)]
pub enum OutputFormat {
    Table,
    Ndjson,
    Json,
}

pub fn run(args: CommandsArgs) -> Result<()> {
    match args.command {
        CommandsCommand::List(args) => list(args),
        CommandsCommand::Docs(args) => docs(args),
    }
}

fn docs(args: DocsArgs) -> Result<()> {
    let body = generate_keybindings_md();
    let path = args
        .out
        .unwrap_or_else(|| std::path::PathBuf::from("docs/keybindings.md"));
    if args.check {
        let existing = std::fs::read_to_string(&path)
            .map_err(|e| anyhow::anyhow!("could not read {}: {e}", path.display()))?;
        if existing != body {
            anyhow::bail!(
                "{} is out of date; regenerate with `ft commands docs --out {}`",
                path.display(),
                path.display()
            );
        }
        Ok(())
    } else {
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)
                .map_err(|e| anyhow::anyhow!("could not create {}: {e}", parent.display()))?;
        }
        std::fs::write(&path, body)
            .map_err(|e| anyhow::anyhow!("could not write {}: {e}", path.display()))?;
        eprintln!("wrote {}", path.display());
        Ok(())
    }
}

/// Walk the command registry, group by scope, and emit a markdown
/// reference. The output is intentionally stable (sorted by name
/// within each scope) so the file is byte-identical across runs as
/// long as the registry hasn't changed.
fn generate_keybindings_md() -> String {
    use std::collections::BTreeMap;
    use std::fmt::Write;

    let reg = registry::build();
    // Group by scope as a stringified key so display order is stable.
    let mut by_scope: BTreeMap<String, Vec<&CommandDef>> = BTreeMap::new();
    for def in reg.iter() {
        by_scope.entry(def.scope.as_str()).or_default().push(def);
    }
    for defs in by_scope.values_mut() {
        defs.sort_by_key(|d| d.name);
    }

    let mut out = String::new();
    writeln!(out, "# Commands & keybindings").unwrap();
    writeln!(out).unwrap();
    writeln!(
        out,
        "Generated by `ft commands docs`. Re-run after modifying any \
         `CommandDef` slice. CI's `ft commands docs --check` verifies this \
         file stays in sync."
    )
    .unwrap();
    writeln!(out).unwrap();

    // Emit a canonical order: global first, then tabs alphabetically,
    // then modals alphabetically.
    let mut scopes: Vec<String> = by_scope.keys().cloned().collect();
    scopes.sort_by(|a, b| {
        let rank = |s: &str| {
            if s == "global" {
                0
            } else if s.starts_with("tab/") {
                1
            } else {
                2
            }
        };
        rank(a).cmp(&rank(b)).then(a.cmp(b))
    });

    for scope in &scopes {
        let defs = &by_scope[scope];
        writeln!(out, "## {scope}").unwrap();
        writeln!(out).unwrap();
        writeln!(out, "| Name | Description | Group | Opens modal |").unwrap();
        writeln!(out, "| --- | --- | --- | --- |").unwrap();
        for def in defs {
            writeln!(
                out,
                "| `{}` | {} | {} | {} |",
                def.name,
                def.description,
                def.group,
                if def.opens_modal { "yes" } else { "no" }
            )
            .unwrap();
        }
        writeln!(out).unwrap();
    }

    out
}

fn list(args: ListArgs) -> Result<()> {
    let reg = registry::build();
    let mut filtered: Vec<&CommandDef> = reg
        .iter()
        .filter(|def| scope_matches(&def.scope, args.scope.as_deref()))
        .filter(|def| args.opens_modal.is_none_or(|v| def.opens_modal == v))
        .collect();
    // Stable order: by scope, then by name.
    filtered.sort_by_key(|d| (d.scope.as_str(), d.name));

    match args.format {
        OutputFormat::Table => print_table(&filtered),
        OutputFormat::Ndjson => print_ndjson(&filtered)?,
        OutputFormat::Json => print_json(&filtered)?,
    }
    Ok(())
}

fn scope_matches(scope: &CommandScope, filter: Option<&str>) -> bool {
    let Some(filter) = filter else { return true };
    match (scope, filter) {
        (CommandScope::Global, "global") => true,
        (CommandScope::Tab(_), "tab") => true,
        (CommandScope::Modal(_), "modal") => true,
        (CommandScope::Tab(t), other) => other == format!("tab/{t}"),
        (CommandScope::Modal(m), other) => other == format!("modal/{m}"),
        _ => false,
    }
}

fn print_table(defs: &[&CommandDef]) {
    use comfy_table::{presets, Cell, Color, ContentArrangement, Table};

    let mut table = Table::new();
    table
        .load_preset(presets::UTF8_FULL)
        .set_content_arrangement(ContentArrangement::Dynamic)
        .set_header(vec![
            Cell::new("Name").fg(Color::Cyan),
            Cell::new("Scope").fg(Color::Cyan),
            Cell::new("Opens modal").fg(Color::Cyan),
            Cell::new("Description").fg(Color::Cyan),
        ]);
    for def in defs {
        table.add_row(vec![
            Cell::new(def.name),
            Cell::new(def.scope.as_str()),
            Cell::new(if def.opens_modal { "yes" } else { "no" }),
            Cell::new(def.description),
        ]);
    }
    println!("{table}");
}

fn print_ndjson(defs: &[&CommandDef]) -> Result<()> {
    for def in defs {
        println!("{}", serde_json::to_string(&serialize_def(def))?);
    }
    Ok(())
}

fn print_json(defs: &[&CommandDef]) -> Result<()> {
    let arr: Vec<serde_json::Value> = defs.iter().map(|d| serialize_def(d)).collect();
    println!("{}", serde_json::to_string_pretty(&arr)?);
    Ok(())
}

fn serialize_def(def: &CommandDef) -> serde_json::Value {
    use serde_json::json;
    let args: Vec<serde_json::Value> = def
        .args_schema
        .iter()
        .map(|a| {
            json!({
                "name": a.name,
                "description": a.description,
                "required": a.required,
            })
        })
        .collect();
    json!({
        "name": def.name,
        "description": def.description,
        "scope": def.scope.as_str(),
        "group": def.group,
        "opens_modal": def.opens_modal,
        "is_primary": def.is_primary,
        "args_schema": args,
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::tui::registry::CommandScope;

    #[test]
    fn scope_matches_filters() {
        assert!(scope_matches(&CommandScope::Global, None));
        assert!(scope_matches(&CommandScope::Global, Some("global")));
        assert!(!scope_matches(&CommandScope::Global, Some("tab")));
        assert!(scope_matches(&CommandScope::Tab("graph"), Some("tab")));
        assert!(scope_matches(
            &CommandScope::Tab("graph"),
            Some("tab/graph")
        ));
        assert!(!scope_matches(
            &CommandScope::Tab("graph"),
            Some("tab/tasks")
        ));
        assert!(scope_matches(
            &CommandScope::Modal("create"),
            Some("modal/create")
        ));
    }

    #[test]
    fn registry_build_includes_known_commands() {
        let reg = registry::build();
        // App globals
        assert!(reg.lookup("app.quit").is_some());
        assert!(reg.lookup("app.next-tab").is_some());
        // Tab commands
        assert!(reg.lookup("graph.create-blank").is_some());
        assert!(reg.lookup("tasks.complete").is_some());
        assert!(reg.lookup("notes.open-picker").is_some());
        assert!(reg.lookup("timeblocks.reload").is_some());
        assert!(reg.lookup("journal.open-picker").is_some());
        // Modal commands
        assert!(reg.lookup("create.confirm").is_some());
        assert!(reg.lookup("query-bar.apply").is_some());
        assert!(reg.lookup("periodic-leader.daily").is_some());
    }

    #[test]
    fn serialize_def_shape() {
        let reg = registry::build();
        let def = reg.lookup("app.quit").unwrap();
        let v = serialize_def(def);
        assert_eq!(v["name"], "app.quit");
        assert_eq!(v["scope"], "global");
        assert_eq!(v["opens_modal"], false);
    }
}
